### ISSUE TITLE
Incorrect optimization for Qiskit circuit?

### ISSUE THREAD

**Issue by bichselb** [Quantomatic/pyzx#134]
Optimizing a simple Qiskit circuit seems to yield a circuit implementing a different unitary.

Here is a minimal example:

```python
import pyzx as zx
from qiskit.circuit import QuantumCircuit

# version
print('Version:', zx.__version__)

# create simple circuit
circuit_qiskit = QuantumCircuit(1)
circuit_qiskit.t(0)
circuit_qiskit.t(0)
circuit_qiskit.t(0)
circuit_qiskit.t(0)
circuit_qiskit.t(0)
circuit = zx.Circuit.from_qasm(circuit_qiskit.qasm())

# optimize
basic = circuit.to_basic_gates()
optimized = zx.optimize.basic_optimization(basic)
optimized_qiskit = QuantumCircuit.from_qasm_str(optimized.to_qasm())

# draw
print('Before optimization:')
print(circuit_qiskit)
# zx.draw(circuit)
print('After optimization:')
# zx.draw(optimized)
print(optimized_qiskit)
```

Here is the output:
```
Version: 0.7.3
Before optimization:
   ┌───┐┌───┐┌───┐┌───┐┌───┐
q: ┤ T ├┤ T ├┤ T ├┤ T ├┤ T ├
   └───┘└───┘└───┘└───┘└───┘
After optimization:
   ┌───┐
q: ┤ T ├
   └───┘
```

Am I doing something wrong?

**Comment by jvdwetering** [comment]
That is definitely a bug in `basic_optimization`. The problem is that it is combining the phases into a single gate, but not updating the name. The one 'T' gate that is in the circuit `optimized` actually has a  `phase` parameter of 5pi/4, but it didn't change the name of the phase gate. If you were to call zx.draw(optimized) you would see that it is still holds the correct phase.

Thanks for reporting, I'm surprised such a basic bug was in this thing.

**Comment by bichselb** [comment]
Ok, thanks for the quick confirmation and detailed explanation!

As this issue is a bottleneck for me, I tried to fix it myself in the pull request above.
