### ISSUE TITLE
`ParityPhase` and `FSim` have parameter order inconsistent with other `Gate`s

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/pyzx#146]
In `Gate` subclasses, the parameters `control`, `target`, and `phase` appear in that order, whenever two or more of them apply to a gate.

The `ParityPhase` gate, however, has the parameters in the order `phase` then `targets` (note the plural).

The `FSim` gate has the parameters in the order `theta`, `phi`, `control`, `target`. 

Based on the other gates, I would've expected the parameters for these to be ordered as `targets` then `phase`, and as `control`, `target`, `theta`, and `phi`, respectively. Then the unwritten rule would be "`control` if it exists, one or more `target`s, followed by one or more `phase`s". 

(Since `ParityPhase` and `FSim` are more complex, there may very well be a good design reason to order the parameters differently for them, but in that case, the reason should be documented and explained.)

**Comment by jvdwetering** [comment]
Since `gates` is a starred parameter, it has to appear last. The other option would be for that parameter to take in a list, in which case it would also be different from the other gates, so I think for `ParityPhase` it is fine.  `FSim` does not have a reason to be different from the other gates and hence could be cleaned up.

**Comment by dlyongemallo** [comment]
If the phases always appeared first, then the `Gate`s could be curried, but I guess it's too late to do that now.
