### ISSUE TITLE
Circuit extraction fails when it shouldn't

### ISSUE THREAD

**Issue by rossduncan** [Quantomatic/pyzx#4]
Title says it all.  The attached zip file contains the "small.qgraph" referenced in the code.  It's obviously a circuit.  After running clifford_simp it's still obviously a circuit, but circuit_extract barfs.

```
file_name = "qgraphs/small.qgraph"
with open(file_name, 'r') as qgraph :
    js = qgraph.read()
    g3 = zx.json_to_graph(js)
    display(zx.draw(g3,labels=True,h_edge_draw='box'))    
    zx.simplify.clifford_simp(g3)
    display(zx.draw(g3,labels=True,h_edge_draw='box'))
    zx.circuit_extract(g3)
```
![screen shot 2018-09-06 at 14 36 33](https://user-images.githubusercontent.com/1511888/45160822-4ac5c380-b1e2-11e8-9940-e0cc39e8ac36.png)

[example.zip](https://github.com/Quantomatic/pyzx/files/2357228/example.zip)

**Comment by johnie102** [comment]
The problem here is that pyzx graphs  need to know what its inputs and outputs are, and these aren't set automatically when importing from a qgraph generated by Quantomatic. With commit 38e67d47b4f5183d6ef72a5f46ce8fafd9c8c770 graphs exported from pyzx set "input" and "output" values in the annotation. I'm up for a better solution if you have some suggestion. 
Anyway, this fixes the problem in your specific case:

   g3 = zx.json_to_graph(js)
   display(zx.draw(g3,labels=True,h_edge_draw='box'))
   g3.inputs = [64,57,50]
   g3.outputs = [65, 63, 46]
   zx.simplify.clifford_simp(g3)
   zx.circuit_extract(g3)

**Comment by rossduncan** [comment]
Thanks John.

A quick and dirty solution I've used in other places is that the input nodes have labels like "in1234" and the outputs like "out5678".  Could you add this?  (I know this example doesn't have the property.)

Since this is a generic problem, I propose this as the standard solution for .qgraph files which are to be interpreted as "circuits", whatever that means.

**Comment by johnie102** [comment]
In 77b7c2a53fc36032f867a7a62fa9813d1c8d1985 I have added a method auto_detect_inputs() that sets the input and output values of a graph to the most left and right nodes of type 0. That should fix the problem in this case.
