### ISSUE TITLE
qubit count and qubit number can be wrong after simplification

### ISSUE THREAD

**Issue by rossduncan** [Quantomatic/pyzx#5]
Seems that the simplifier sometimes messes up the qubit numbering.  In particular sometimes the qubit index can be negative (which I think is a bug but maybe you want to allow it) and the qubit count is off.  For example, the following obviously has three qubits but qubit count reports only 1.

(Also I think that both these methods should return ints not floats but opinions may differ)

```
file_name = "qgraphs/small.qgraph"
with open(file_name, 'r') as qgraph :
    js = qgraph.read()
    g3 = zx.json_to_graph(js)
    zx.simplify.clifford_simp(g3)
    display(zx.draw(g3,labels=True,h_edge_draw='box'))
    count = g3.qubit_count()
    index = g3.qubit(28)
    print("qubit count : " + str(count))
    print("qubit index of vertex 28 : " + str(index))
```
![screen shot 2018-09-06 at 15 12 43](https://user-images.githubusercontent.com/1511888/45163068-59fb4000-b1e7-11e8-8f4a-7de0f50e0bdd.png)

[example.zip](https://github.com/Quantomatic/pyzx/files/2357407/example.zip)

**Comment by johnie102** [comment]
Since commit 0ea2c417933b2b51247cf29f2dff4c03196e9a7e `g3.normalise()` will normalise the qubit numbers so that the inputs are on qubit values 0, 1, 2, .... The qubit_count() currently returns the highest qubit value, which I agree is not very intuitive, and the function might best be renamed. To get the amount of actual qubits you could use something like `len(g3.inputs)` when input and output nodes are specified (which they wouldn't be in your case since you are importing from a qgraph file).

**Comment by akissinger** [comment]
n.b. As a hack for quanto inter-operability, the qubit index is stored simply as minus the Y-coordinate in the qgraph. So, positive Y-coordinates = negative qubit indices. Since the qubit count is the max of the qubit indices + 1, you can see how this will go wrong. I guess this also explains why these end up floats and not ints for you.

Generally, giving pyzx a circuit (in either QASM or Quipper ASCII format) is more reliable than giving it a circuit-like qgraph file.

**Comment by rossduncan** [comment]
Thanks guys.
I suggest that :
* the qubit_count() always returns to an int (just put the cast in the return statement)
* that it returns one more than it does right now

Would it break quanto interoperability if the y-coords were all normalised to positive integers?

**Comment by obtext** [comment]
> Yes, I've been thinking of changing this function to simply return the amount of nodes that are labelled as inputs, as this makes more sense.

Seems a good idea, and it's what the name implies, even if it's not how it's currently documented ("the value of the highest qubit index given to a vertex"). Currently both the name _and_ the documentation are wrong (since it's actually one more than the highest qubit index):
```
g = zx.Graph()
g.add_vertices(2)
q = 1 # single qubit index
g.set_position(0,q,0)
g.set_position(1,q,1)
g.add_edge((0,1))
g.inputs = [0]
g.outputs = [1]

qs = set(g.qubits().values()) # {1}
g.qubit_count(), len(qs), max(qs)
>>> (2, 1, 1)
```
